/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import Clases.TipoCambioConexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;

/**
 *
 * @author Leonardo
 */
public class FMonedas extends javax.swing.JFrame {

    int xMouse,yMouse;
    Color colorPrincipal = new Color(13, 46, 89);
    Color colorSecundario = new Color(242,242,242);
    private static final DecimalFormat df = new DecimalFormat("0.00");

    public FMonedas() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        PanelMenus = new javax.swing.JPanel();
        PanelBtnConvertir = new javax.swing.JPanel();
        BtnConvertir = new javax.swing.JLabel();
        PanelSuperior = new javax.swing.JPanel();
        PanelBtnCierre = new javax.swing.JPanel();
        BtnCierre = new javax.swing.JLabel();
        TituloConversor = new javax.swing.JLabel();
        TituloConversor1 = new javax.swing.JLabel();
        CmbMoneda1 = new javax.swing.JComboBox<>();
        CmbMoneda2 = new javax.swing.JComboBox<>();
        Txt_Monto1 = new javax.swing.JTextField();
        Txt_Monto2 = new javax.swing.JTextField();
        Txt_TipoCambio = new javax.swing.JTextField();
        TituloTipoCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        PanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTitulo.setBackground(new java.awt.Color(13, 46, 89));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/github_social.png"))); // NOI18N

        titulo1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setText("MONEDAS");

        titulo2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setText("CONVERSOR");

        titulo3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setText("< Regresar");
        titulo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titulo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titulo3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                        .addComponent(titulo2)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                        .addComponent(titulo1)
                        .addGap(50, 50, 50))))
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(logo))
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(titulo3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo1)
                .addGap(146, 146, 146)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelFondo.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        PanelBtnConvertir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 46, 89), 2));

        BtnConvertir.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        BtnConvertir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/convertir.png"))); // NOI18N
        BtnConvertir.setText("CONVERTIR");
        BtnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConvertirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnConvertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnConvertirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnConvertirLayout = new javax.swing.GroupLayout(PanelBtnConvertir);
        PanelBtnConvertir.setLayout(PanelBtnConvertirLayout);
        PanelBtnConvertirLayout.setHorizontalGroup(
            PanelBtnConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnConvertir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        PanelBtnConvertirLayout.setVerticalGroup(
            PanelBtnConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PanelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelSuperiorMouseDragged(evt);
            }
        });
        PanelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSuperiorMousePressed(evt);
            }
        });

        BtnCierre.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        BtnCierre.setForeground(new java.awt.Color(13, 46, 89));
        BtnCierre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCierre.setText("X");
        BtnCierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCierreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnCierreLayout = new javax.swing.GroupLayout(PanelBtnCierre);
        PanelBtnCierre.setLayout(PanelBtnCierreLayout);
        PanelBtnCierreLayout.setHorizontalGroup(
            PanelBtnCierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnCierre, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );
        PanelBtnCierreLayout.setVerticalGroup(
            PanelBtnCierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnCierreLayout.createSequentialGroup()
                .addComponent(BtnCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(PanelBtnCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBtnCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TituloConversor.setBackground(new java.awt.Color(13, 46, 89));
        TituloConversor.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        TituloConversor.setForeground(new java.awt.Color(13, 46, 89));
        TituloConversor.setText("SELECCIONE LAS MONEDAS");

        TituloConversor1.setBackground(new java.awt.Color(13, 46, 89));
        TituloConversor1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        TituloConversor1.setForeground(new java.awt.Color(13, 46, 89));
        TituloConversor1.setText("->");

        CmbMoneda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD|Dolares", "EUR|Euros", "MXN|Pesos Mexicanos", "BRL|Real Brasileño", "PEN|Soles" }));

        CmbMoneda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD|Dolares", "EUR|Euros", "MXN|Pesos Mexicanos", "BRL|Real Brasileño", "PEN|Soles" }));

        Txt_Monto1.setText("0");

        Txt_Monto2.setText("0");

        Txt_TipoCambio.setEditable(false);
        Txt_TipoCambio.setText("0");

        TituloTipoCambio.setBackground(new java.awt.Color(13, 46, 89));
        TituloTipoCambio.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        TituloTipoCambio.setForeground(new java.awt.Color(13, 46, 89));
        TituloTipoCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloTipoCambio.setText("Tipo de Cambio");

        javax.swing.GroupLayout PanelMenusLayout = new javax.swing.GroupLayout(PanelMenus);
        PanelMenus.setLayout(PanelMenusLayout);
        PanelMenusLayout.setHorizontalGroup(
            PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenusLayout.createSequentialGroup()
                        .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CmbMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloConversor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(PanelMenusLayout.createSequentialGroup()
                .addGroup(PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenusLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(TituloConversor))
                    .addGroup(PanelMenusLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(PanelBtnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelMenusLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_TipoCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(TituloTipoCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelMenusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Txt_Monto1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_Monto2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        PanelMenusLayout.setVerticalGroup(
            PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenusLayout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TituloConversor)
                .addGap(18, 18, 18)
                .addGroup(PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloConversor1)
                    .addComponent(CmbMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Monto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Monto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(TituloTipoCambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_TipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(PanelBtnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        PanelFondo.add(PanelMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 370, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
        
    }//GEN-LAST:event_PanelSuperiorMousePressed

    private void PanelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_PanelSuperiorMouseDragged

    private void BtnCierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BtnCierreMouseClicked

    private void BtnCierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCierreMouseEntered
        BtnCierre.setForeground(Color.red);
    }//GEN-LAST:event_BtnCierreMouseEntered

    private void BtnCierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCierreMouseExited
        BtnCierre.setForeground(colorPrincipal);
    }//GEN-LAST:event_BtnCierreMouseExited

    private void BtnConvertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConvertirMouseEntered
        BtnConvertir.setForeground(Color.white);
        PanelBtnConvertir.setBackground(colorPrincipal);
    }//GEN-LAST:event_BtnConvertirMouseEntered

    private void BtnConvertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConvertirMouseExited
        BtnConvertir.setForeground(Color.black);
        PanelBtnConvertir.setBackground(colorSecundario);
    }//GEN-LAST:event_BtnConvertirMouseExited

    private void titulo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titulo3MouseClicked
        FPrincipal vtnPrincipal = new FPrincipal();
        vtnPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_titulo3MouseClicked

    private void BtnConvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConvertirMouseClicked
        /*OBTENIENDO VALORES*/
        String comboMoneda1 = CmbMoneda1.getSelectedItem().toString();
        String[] comboMoneda1Valores = comboMoneda1.split("\\|");
        String base = comboMoneda1Valores[0];
        
        String comboMoneda2 = CmbMoneda2.getSelectedItem().toString();
        String[] comboMoneda2Valores = comboMoneda2.split("\\|");
        String busqueda = comboMoneda2Valores[0];
        
        /*
        if ("USD".equals(base)) {
            System.out.println("Es USD");
        }

        if ("USD".equals(busqueda)) {
            System.out.println("Es USD 2");
        }*/

        /*TIPO DE CAMBIO*/
        TipoCambioConexion busquedaTipoCambio = new TipoCambioConexion();
        Double tipoCambio = busquedaTipoCambio.consulta(base, busqueda);
        
        
        /*JTEXTS*/
        Double valorMonto1 = Double.parseDouble(Txt_Monto1.getText());
        
        /*CALCULO*/
        Double valorMonto2 = valorMonto1 * tipoCambio;
        
        /*PONIENDO DATOS*/
        Txt_Monto2.setText(Double.toString(valorMonto2));
        Txt_TipoCambio.setText(Double.toString(tipoCambio));
        
        
        
        //System.out.println(base +"-" + busqueda);
        System.out.println(valorMonto2);
        System.out.println(tipoCambio);
        System.out.println(valorMonto2);
        
    }//GEN-LAST:event_BtnConvertirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCierre;
    private javax.swing.JLabel BtnConvertir;
    private javax.swing.JComboBox<String> CmbMoneda1;
    private javax.swing.JComboBox<String> CmbMoneda2;
    private javax.swing.JPanel PanelBtnCierre;
    private javax.swing.JPanel PanelBtnConvertir;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelMenus;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel TituloConversor;
    private javax.swing.JLabel TituloConversor1;
    private javax.swing.JLabel TituloTipoCambio;
    private javax.swing.JTextField Txt_Monto1;
    private javax.swing.JTextField Txt_Monto2;
    private javax.swing.JTextField Txt_TipoCambio;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
